.TH LOGFORW-SHUTDOWN "1" "2012-01-16" "Log forward utility" "User Commands"

.SH NAME
logforw-stop \- stop all log forward daemons

.SH SYNOPSYS
.B logforw-stop

.SH DESCRIPTION
This is a utility script which will shut down all running
log forward daemons.

Also, it will stop the errpt background reporting daemon if
it was running.

