#!/bin/sh

# Shut down the log forward daemon.

# Const.
SUCCESS=0
FAILURE=1

# Print help.
case $1 in
-h|-help|--help)
	cat <<!EOF
This script is to stop all running log forward daemons.
Usage:
    logforw-stop
!EOF
	exit $FAILURE
	;;
esac

# Get pids of the running daemon(s) and kill them.
ps -ef | egrep -e '/logforw |logforw ' | grep -v grep | \
while read USERNAME PID REST
do
	kill $PID
done

# An another round with -9 in case it was still hanging around.
sleep 1
ps -ef | egrep -e '/logforw |logforw ' | grep -v grep | \
while read USERNAME PID REST
do
	kill -9 $PID
done

# Also kill errpt -c if that was running.
ps -ef | egrep -e '/errpt -c |errpt -c ' | grep -v grep | \
while read USERNAME PID REST
do
	kill $PID
	sleep 1
	if ps $PID >/dev/null 2>&1
	then
		kill -9 $PID
	fi
done

# Finish.
exit $SUCCESS

